[package]
name = "learnopengl"
version = "0.1.0"
edition = "2021"

[lib]
name = "learnopengl"
path = "src/lib.rs"

[dependencies]
gl = "0.14.0"
nalgebra = "0.30.1"
num-traits = "0.2.14"
sdl2 = "0.35.1"
